name: 'Get Shaderc'
description: 'Builds Shaderc from source'

inputs:
  source_dir:
    description: ''
    required: false
    default: 'SHADERC_DIR'
  build_mode:
    description: ''
    required: false
    default: Release

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      git clone https://github.com/google/shaderc ${{inputs.source_dir}}
      cd ${{inputs.source_dir}}
      ./utils/git-sync-deps

  - shell: bash
    run: |
      cmake ${{inputs.source_dir}}
      cmake --build build/shaderc --source ${{inputs.source_dir}}

