name: Get Dependencies

runs:
  using: 'composite'

  steps:
  - if: runner.os == 'Linux'
    run: sudo apt update && sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libc6-dev && export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH

  - uses: humbletim/setup-vulkan-sdk@72eed4b9dbeac5de168f83da8e30b1d0f8ac7f14 # v1.2.0
    with:
      vulkan-query-version: 1.3.204.0 
      vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
      vulkan-use-cache: true

