name: cmake-android

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

permissions:
  contents: read

jobs:
  android:
    concurrency:
      group: '${{ matrix.type }} ${{ matrix.cfg }} ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true

    name: Android
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [ BUILD_SHARED_LIBS=OFF, BUILD_SHARED_LIBS=ON ]
        cfg: [ Debug, Release ]
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive

    - uses: ./.github/actions/get_deps

    - uses: ./.github/actions/build
      with:
        type: ${{ matrix.type }}
        config: ${{ matrix.cfg }}