name: cmake-ios

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

permissions:
  contents: read

jobs:
  ios:
    name: iOS
    runs-on: macos-latest

    strategy:
      matrix:
        type: [ BUILD_SHARED_LIBS=OFF, BUILD_SHARED_LIBS=ON ]
        cfg: [ Debug, Release ]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: latest-stable
    - uses: humbletim/setup-vulkan-sdk@72eed4b9dbeac5de168f83da8e30b1d0f8ac7f14 # v1.2.0
      with:
        vulkan-query-version: latest 
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
        vulkan-use-cache: true
    - run: |
        cmake . -B build -D${{ matrix.type }} --install-prefix ${{ github.workspace }}/install -DCMAKE_INSTALL_DIR=${{ github.workspace }}/install -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.cfg }}
        cmake --install ${{ github.workspace }}/build --config ${{ matrix.cfg }}
